load("@rules_apple//apple:ios.bzl", "ios_framework")
load("@rules_cc//cc:defs.bzl", "objc_library")

objc_library(
    name = "ios",
    srcs = glob([
        "*.c",
        "*.h",
    ]),
    target_compatible_with = ["@platforms//os:ios"],
    visibility = ["//touchcontroller:__subpackages__"],
    alwayslink = True,
    deps = [
        "//touchcontroller/proxy/server/util/ringbuffer",
        "@rules_jni//jni",
    ],
)

ios_framework(
    name = "touchcontroller_proxy",
    bundle_id = "top.fifthlight.touchcontroller.proxy.ios",
    families = ["iphone", "ipad"],
    minimum_os_version = "14.0",
    infoplists = ["Info.plist"],
    hdrs = ["ios.h"],
    deps = [":ios"],
)